/* eslint-disable @typescript-eslint/no-misused-promises */
import moment, { Moment } from "moment";
import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { HTMLInputTypeAttribute, useCallback, useEffect } from "react";
import { useState } from "react";

import Datetime from "react-datetime";
import Navbar from "../components/Navbar";

type Shift = {
  id: string;
  created_at: string;
  start_time: string;
  break_minutes: number;
  end_time: string;
};
const Home: NextPage = () => {
  const { data: session, status } = useSession();
  const [data, setData] = useState<Shift[]>([]);
  const fetchData = async () => {
    const BASE_URL = process.env.NEXTAUTH_URL ?? "";

    const response = await fetch(`${BASE_URL}/api/shifts/getShifts`, {
      method: "POST",
      body: JSON.stringify({
        userId: session?.user?.id,
      }),
      headers: {
        "Content-type": "application/json; charset=UTF-8",
      },
    });
    const newData = (await response.json()) as Shift[];
    setData(newData);
  };

  useEffect(() => {
    void fetchData();
  }, [session?.user?.id]);

  function getHours(shift: Shift) {
    const SECS_IN_A_MIN = 60;
    const MS_IN_A_SEC = 1000;
    const MIN_IN_HOUR = 60;
    const diff =
      moment(shift.end_time).diff(moment(shift.start_time)) /
      SECS_IN_A_MIN /
      MS_IN_A_SEC;
    const hours = Math.floor((diff - shift.break_minutes) / MIN_IN_HOUR);
    const mins = (diff - shift.break_minutes) % MIN_IN_HOUR;

    return `${hours}:${mins.toString().padStart(2, "0")}`;
  }

  async function onDelete(shiftId: string) {
    const BASE_URL = process.env.NEXTAUTH_URL ?? "";
    await fetch(`${BASE_URL}/api/shifts/deleteShift`, {
      method: "POST",
      body: JSON.stringify({
        id: shiftId,
      }),
      headers: {
        "Content-type": "application/json; charset=UTF-8",
      },
    }).then((res) => fetchData());
  }

  const headers = [
    "Created At",
    "Start Time",
    "End Time",
    "Break (minutes)",
    "Hours",
  ];
  return (
    <>
      <Head>
        <title>Payroll App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">My</span> Shifts
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-1 md:gap-8">
            <div className="hidden grid-cols-1 rounded-xl bg-purple-700 p-4 text-white sm:grid  sm:grid-cols-6">
              {headers.map((header, i) => (
                <p className="font-bold" key={i}>
                  {header}
                </p>
              ))}
            </div>
            {data.map((shift, i) => (
              <div
                key={i}
                className="grid grid-cols-1 place-items-center rounded-xl bg-purple-700 p-4 text-white sm:grid-cols-6"
              >
                <p>
                  <span className="font-bold sm:hidden">Created At: </span>
                  {moment(shift.created_at).format("LLLL")}
                </p>
                <p>
                  <span className="font-bold sm:hidden">Start Time: </span>
                  {moment(shift.start_time).format("LLLL")}
                </p>
                <p>
                  <span className="font-bold sm:hidden">End Time: </span>
                  {moment(shift.end_time).format("LLLL")}
                </p>
                <p className="">
                  <span className="font-bold sm:hidden">Break (minutes): </span>
                  {shift.break_minutes}
                </p>
                <p>
                  <span className="font-bold sm:hidden">Hours: </span>
                  {getHours(shift)}
                </p>
                <div
                  onClick={() => onDelete(shift.id)}
                  className="mt-4 flex h-12 w-24 cursor-pointer items-center justify-center rounded-xl border-b-2 border-red-900 bg-red-500 p-2 hover:bg-red-600"
                >
                  Delete
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
